#!/usr/bin/env bash
# Builds libqemu-aarch64-softmmu.dylib for arm64 iOS from emulator/src
# (emulator/scripts/fetch.sh) against the prefix from build-ios-deps.sh.
#
#   PREFIX=$PWD/prefix emulator/scripts/build-ios.sh
#
# Output: build/emulator/libqemu-aarch64-softmmu.dylib
# The meson options follow Inferno-iOS (docs/UPSTREAM.md): shared_lib turns the
# emulator into a library; ucontext replaces the coroutine backend because iOS
# has no usable sigaltstack; VNC stays compiled in as upstream builds it.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
LOCK="$ROOT/tools/deps/lockfile.py"
SRC="${EMULATOR_SRC:-$ROOT/emulator/src}"
PREFIX="${PREFIX:-$ROOT/prefix}"
BUILD="${EMULATOR_BUILD:-$ROOT/build/emulator}"
DEPLOY="${DEPLOY:-$(python3 "$LOCK" get toolchain.ios_deployment_target)}"
CROSS="$BUILD/cross-ios-arm64.txt"

[ -f "$SRC/.vp-patched" ] || { echo "no prepared emulator tree at $SRC; run emulator/scripts/fetch.sh" >&2; exit 1; }
[ -d "$PREFIX/lib" ] || { echo "no dependency prefix at $PREFIX; run emulator/scripts/build-ios-deps.sh" >&2; exit 1; }
want="$(python3 "$LOCK" deps-hash)"
have="$(cat "$PREFIX/.deps-lock-hash" 2>/dev/null || true)"
[ "$want" = "$have" ] || { echo "prefix was built from a different deps.lock ($have != $want)" >&2; exit 1; }

CMAKE="$(command -v cmake || true)"
[ -n "$CMAKE" ] || { echo "cmake not found (brew install cmake): the libyuv subproject needs it" >&2; exit 1; }
SDK="$(xcrun --sdk iphoneos --show-sdk-path)"
BIN="$(dirname "$(xcrun --sdk iphoneos --find ar)")"
FLAGS="'-arch', 'arm64', '-isysroot', '$SDK', '-mios-version-min=$DEPLOY'"

mkdir -p "$BUILD"
# Meson cross-files take no variables, so absolute paths are generated here.
cat > "$CROSS" <<EOF
# Generated by emulator/scripts/build-ios.sh — edit the script, not this file.
[binaries]
c          = 'clang'
cpp        = 'clang++'
objc       = 'clang'
ar         = '$BIN/ar'
strip      = '$BIN/strip'
ranlib     = '$BIN/ranlib'
pkg-config = 'pkg-config'
cmake      = '$CMAKE'

[built-in options]
c_args         = [$FLAGS, '-I$PREFIX/include']
c_link_args    = [$FLAGS, '-L$PREFIX/lib', '-framework', 'CoreFoundation', '-lucontext']
cpp_args       = [$FLAGS, '-I$PREFIX/include']
# libyuv is C++, so the final dylib is linked by clang++ with these.
cpp_link_args  = [$FLAGS, '-L$PREFIX/lib', '-framework', 'CoreFoundation', '-lucontext']
objc_args      = [$FLAGS]
# Without this, a target with one Objective-C file links for the host.
objc_link_args = [$FLAGS, '-L$PREFIX/lib', '-framework', 'CoreFoundation', '-lucontext']
prefix         = '$PREFIX'

[host_machine]
system     = 'darwin'
subsystem  = 'ios'
kernel     = 'xnu'
cpu_family = 'aarch64'
cpu        = 'aarch64'
endian     = 'little'

[properties]
needs_exe_wrapper = true
pkg_config_libdir = ['$PREFIX/lib/pkgconfig']

# libyuv (hw/display) is a CMake subproject. These go into the CMake toolchain
# meson generates: build for iOS against the same SDK, and leave JPEG out so
# CMake cannot pick up a macOS libjpeg from Homebrew.
[cmake]
CMAKE_SYSTEM_NAME = 'iOS'
CMAKE_SYSTEM_PROCESSOR = 'aarch64'
CMAKE_OSX_SYSROOT = '$SDK'
CMAKE_OSX_ARCHITECTURES = 'arm64'
CMAKE_OSX_DEPLOYMENT_TARGET = '$DEPLOY'
CMAKE_FIND_ROOT_PATH = '$PREFIX'
LIBYUV_DISABLE_JPEG = 'ON'
CMAKE_DISABLE_FIND_PACKAGE_JPEG = 'TRUE'
EOF

if [ ! -f "$BUILD/meson/build.ninja" ]; then
    meson setup "$BUILD/meson" "$SRC" \
        --cross-file="$CROSS" \
        -Dbuildtype=release -Dprefix="$PREFIX" \
        -Dshared_lib=true -Db_staticpic=true -Dwerror=false \
        -Dkvm=disabled -Dhvf=disabled -Dwhpx=disabled \
        -Dcocoa=disabled -Dgtk=disabled -Dsdl=disabled -Dcurses=disabled \
        -Dcoreaudio=disabled -Dcurl=disabled -Dlibssh=disabled -Dbzip2=disabled \
        -Dvnc=enabled -Dvnc_jpeg=disabled -Dvnc_sasl=disabled \
        -Dtools=disabled -Dcoroutine_backend=ucontext
fi
ninja -C "$BUILD/meson" libqemu-aarch64-softmmu.dylib

cp "$BUILD/meson/libqemu-aarch64-softmmu.dylib" "$BUILD/"
DYLIB="$BUILD/libqemu-aarch64-softmmu.dylib"

# The bridge resolves these by name; a build that lost them is useless.
# Listed once into a variable: `nm | grep -q` would SIGPIPE nm under pipefail.
exports="$(nm -gU "$DYLIB" | awk '{print $3}')"
missing=0
for sym in qemu_init qemu_main_loop qemu_cleanup inferno_display_attach inferno_display_read \
           inferno_input_touch inferno_input_function_key qemu_system_shutdown_request \
           qemu_system_vmstop_request qemu_system_vmstop_request_prepare vm_start bql_lock_impl; do
    if ! grep -qx "_$sym" <<<"$exports"; then
        echo "missing export: $sym" >&2
        missing=1
    fi
done
[ "$missing" = 0 ] || exit 1
lipo -info "$DYLIB"
ls -lh "$DYLIB"
